%% Main Function (Direction Parameters Revised)
function classify_tourism_type(city_name, params)
    dims = {'E','I','C'}; 
    
    indicators = {...
        {'glacier_ratio', 'endangered_density', 'co2_per_tourist', 'recovery_years'},... % E dimension
        {'overload_rate', 'water_stress', 'congestion_cost', 'emergency_coverage'},...  % I dimension
        {'heritage_density', 'craft_transmission', 'language_diversity', 'culture_conflict'}}; % C dimension
    
    % Direction parameter revision: 1 = higher value indicates more severe issue, -1 = opposite
    directions = {[-1, 1, 1, 1], [1, 1, 1, -1], [-1, -1, -1, 1]}; % corrected directions

    [scores, weights] = process_dimensions(params, indicators, directions);
    type = determine_type(scores);
    visualize_results(city_name, scores, weights, dims, type);
end

%% Data Processing Function
function [scores, weights] = process_dimensions(params, indicators, directions)
    scores = zeros(1,3);
    weights = zeros(1,3);
    
    for d = 1:3
        raw_data = cellfun(@(x)params.(x), indicators{d});
        [norm_data, dim_weights] = entropy_weighting(raw_data, directions{d});
        scores(d) = sum(norm_data .* dim_weights);
        weights(d) = sum(dim_weights);
    end
    weights = weights / sum(weights);
end

%% Entropy Weighting Calculation
function [normalized, weights] = entropy_weighting(data, direction)
    n = length(data);
    normalized = zeros(1,n);
    
    if max(data) ~= min(data)
        for i = 1:n
            if direction(i) == 1 % larger value = more severe
                normalized(i) = (data(i) - min(data)) / (max(data) - min(data));
            else % smaller value = more severe
                normalized(i) = (max(data) - data(i)) / (max(data) - min(data));
            end
        end
    else
        normalized = ones(1,n);
    end
    
    p = normalized ./ (sum(normalized) + eps);
    e = -sum(p .* log(p + eps)) / log(n + eps);
    weights = (1 - e) / sum(1 - e);
end

%% Type Determination Function
function type = determine_type(scores)
    % Parameter settings
    SINGLE_THRESHOLD = 0.4;  % Dominant single-dimension threshold
    COMBO_THRESHOLD = 0.7;   % Two-dimension combined threshold
    dims = {'E','I','C'};
    
    % Normalize dimension scores
    total = sum(scores);
    norm_scores = scores / total;
    
    % Find the dimension with the highest score (most severe problem)
    [max_score, main_dim] = max(norm_scores);
    
    % Single-dimension dominant type
    if max_score >= SINGLE_THRESHOLD
        type = [dims{main_dim} ' Dominant Type'];
        return
    end
    
    % Two-dimension combined type (top 2 dimensions)
    sorted_scores = sort(norm_scores, 'descend');
    if sum(sorted_scores(1:2)) >= COMBO_THRESHOLD
        [~, idx] = maxk(norm_scores, 2);
        combo_dims = sort(idx); % alphabetical order
        type = [dims{combo_dims(1)} '-' dims{combo_dims(2)} ' Combined Type'];
        return
    end
    
    % Balanced comprehensive type
    if max(norm_scores) - min(norm_scores) < 0.15
        type = 'Balanced Comprehensive Type';
    else
        type = 'Unclear Type';
    end
end

%% Visualization Function
function visualize_results(city_name, scores, weights, dims, type)
    figure('Position', [200 200 1000 420], 'Color', 'w')
    
    % Scores vs Weights Comparison
    subplot(1,3,1)
    bar([scores/max(scores); weights]')
    set(gca, 'XTickLabel', dims, 'FontSize',9)
    title('Dimension Comparison')
    legend({'Normalized Score','Weight Share'}, 'FontSize',8)
    grid on
    
    % 3D Radar Chart
    subplot(1,3,2)
    radar_data = [scores, scores(1)];
    theta = linspace(0, 2*pi, 4);
    polarplot(theta, radar_data, 'LineWidth',2)
    thetaticklabels(dims)
    rlim([0 max(scores)*1.2])
    title('3D Capability Radar')
    
    % Type Annotation
    subplot(1,3,3)
    text(0.5,0.5, type, ...
        'FontSize',16, 'Color',[0.9 0.2 0.2], ...
        'HorizontalAlignment','center', ...
        'FontWeight','bold')
    axis off
    title('Final Determined Type')
    
    sgtitle([city_name ' Tourism Type Intelligent Analysis'], 'FontSize',14, 'Color',[0.3 0.3 0.3])
end

%% Test Cases (7 types validation)
% 1. E Dominant Type (Severe Ecological Issues)
CASE1 = struct(...
    'glacier_ratio',       0.05,  ...
    'endangered_density',  0.85,  ...
    'co2_per_tourist',     18.2, ...
    'recovery_years',      25,   ...
    'overload_rate',       65,   ...
    'water_stress',        3.2,  ...
    'congestion_cost',     12.5, ...
    'emergency_coverage',  0.75, ...
    'heritage_density',    2.8,  ...
    'craft_transmission',  0.62, ...
    'language_diversity',  0.45, ...
    'culture_conflict',    0.32);
classify_tourism_type('Venice (Italy)', CASE1)

% 2. I Dominant Type (Infrastructure Issues)
CASE2 = struct(...
    'glacier_ratio',       0.88, ...
    'endangered_density',  0.12, ...
    'co2_per_tourist',     0.06, ...
    'recovery_years',      3, ...
    'overload_rate',       98, ...
    'water_stress',        6.7, ...
    'congestion_cost',     42.3, ...
    'emergency_coverage',  0.28, ...
    'heritage_density',    3.5, ...
    'craft_transmission',  0.71, ...
    'language_diversity',  0.58, ...
    'culture_conflict',    0.39);
classify_tourism_type('Mumbai (India)', CASE2)

% 3. C Dominant Type (Cultural Issues)
CASE3 = struct(...
    'glacier_ratio',       0.88, ...
    'endangered_density',  0.01, ...
    'co2_per_tourist',     1, ...
    'recovery_years',      1, ...
    'overload_rate',       35, ...
    'water_stress',        1.2, ...
    'congestion_cost',     7.8, ...
    'emergency_coverage',  0.92, ...
    'heritage_density',    0.8, ...
    'craft_transmission',  0.15, ...
    'language_diversity',  0.12, ...
    'culture_conflict',    0.83);
classify_tourism_type('Barcelona (Spain)', CASE3)

% 4. E-I Combined Type
CASE4 = struct(...
    'glacier_ratio',       0.12, ...
    'endangered_density',  0.63, ...
    'co2_per_tourist',     12.5, ...
    'recovery_years',      18, ...
    'overload_rate',       89, ...
    'water_stress',        4.8, ...
    'congestion_cost',     32.1, ...
    'emergency_coverage',  0.41, ...
    'heritage_density',    2.1, ...
    'craft_transmission',  0.53, ...
    'language_diversity',  0.37, ...
    'culture_conflict',    0.45);
classify_tourism_type('Reykjavik (Iceland)', CASE4)

% 5. C-I Combined Type
CASE5 = struct(...
    'glacier_ratio',       0.99, ...
    'endangered_density',  0.01, ...
    'co2_per_tourist',     1, ...
    'recovery_years',      1, ...
    'overload_rate',      99, ...
    'water_stress',        12.9, ...
    'congestion_cost',     19.8, ...
    'emergency_coverage',  0.21, ...
    'heritage_density',    1, ...
    'craft_transmission',  0.01, ...
    'language_diversity',  0.23, ...
    'culture_conflict',    0.98);
classify_tourism_type('Athens (Greece)', CASE5)

% 6. E-C Combined Type
CASE6 = struct(...
    'glacier_ratio',       0.06, ...
    'endangered_density',  0.72, ...
    'co2_per_tourist',     14.8, ...
    'recovery_years',      22, ...
    'overload_rate',       58, ...
    'water_stress',        2.3, ...
    'congestion_cost',     14.2, ...
    'emergency_coverage',  0.67, ...
    'heritage_density',    0.9, ...
    'craft_transmission',  0.24, ...
    'language_diversity',  0.33, ...
    'culture_conflict',    0.81);
classify_tourism_type('Kyoto (Japan)', CASE6)

% 7. Balanced Comprehensive Type
CASE7 = struct(...
    'glacier_ratio',       0.42, ...
    'endangered_density',  0.09, ...
    'co2_per_tourist',     2.9, ...
    'recovery_years',      5, ...
    'overload_rate',       93, ...
    'water_stress',        5.6, ...
    'congestion_cost',     38.7, ...
    'emergency_coverage',  0.33, ...
    'heritage_density',    0.7, ...
    'craft_transmission',  0.18, ...
    'language_diversity',  0.21, ...
    'culture_conflict',    0.78);
classify_tourism_type('Singapore', CASE7)